stages:
  - build

build_esp32_p4x_eye:
  stage: build
  image: espressif/idf:v5.5.3
  tags:
    - build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
  before_script:
    - git submodule update --init --depth=1 --no-single-branch
    - git -C lib/micropython/ submodule update --init --depth=1
  script:
    - . /opt/esp/idf/export.sh
    - make -j$(nproc) TARGET=ESP32_P4X_EYE
  artifacts:
    when: on_success
    paths:
      - build/bin/
    expire_in: 1 week
