/*
 * This file is part of the OpenMV project.
 *
 * Image library configuration.
 */
#ifndef __IMLIB_CONFIG_H__
#define __IMLIB_CONFIG_H__

#define IMLIB_ENABLE_IMAGE_IO
#define IMLIB_ENABLE_IMAGE_FILE_IO
#define IMLIB_ENABLE_LAB_LUT
#define IMLIB_ENABLE_BINARY_OPS
#define IMLIB_ENABLE_MATH_OPS
#define IMLIB_ENABLE_MEAN
#define IMLIB_ENABLE_MEDIAN
#define IMLIB_ENABLE_MODE
#define IMLIB_ENABLE_MIDPOINT
#define IMLIB_ENABLE_MORPH
#define IMLIB_ENABLE_GAUSSIAN
#define IMLIB_ENABLE_LAPLACIAN
#define IMLIB_ENABLE_BILATERAL
#define IMLIB_ENABLE_QRCODES
#define IMLIB_FIND_TEMPLATE

#endif // __IMLIB_CONFIG_H__
